//Teste de Requisições REST - Estudantes
@baseURL = http://localhost:4000
@id = 6187d99da683f53cf61a74b7
###
// GET - Lista todos os estudantes
GET {{baseURL}}/estudantes
Content-Type: application/json

###
// GET - Lista apenas um estudante pelo id
GET {{baseURL}}/estudantes/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo estudante
POST {{baseURL}}/estudantes
Content-Type: application/json

{
   "nome":"Maria Ivone Lima 6",
   "anoGraduação":2048,
   "tipo":"Estudante",
   "notaMédia":4.73,
   "endereço": {
      "logradouro":"Av.Tiradentes, 1211",
      "municipio":"Itu"
      }
}

### 
// DELETE - Apaga um estudante através do id informado
DELETE {{baseURL}}/estudantes/{{id}}
Content-Type: application/json

###
// PUT - Altera um estudante pelo ID
PUT {{baseURL}}/estudantes
Content-Type: application/json

{
    "_id": "6187d99da683f53cf61a74b7", 
    "nome":"Alterado Maria Ivone Lima 6",
   "anoGraduação":2048,
   "tipo":"Estudante",
   "notaMédia":4.73,
   "endereço": {
      "logradouro":"altera Av.Tiradentes, 1211",
      "municipio":" altera Itu"
      }
}


