//Teste de Requisições REST - Usuários
//@baseURL = https://backdogwalker.herokuapp.com/api
@baseURL = http://localhost:4000/api
@id = 619d068ef455b2ded14c3af4
###
// GET - Lista todos os usuários
GET {{baseURL}}/usuarios
Content-Type: application/json

###
// GET - Lista apenas um usuário pelo id
GET {{baseURL}}/usuarios/id/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo usuário
POST {{baseURL}}/usuarios
Content-Type: application/json

{
   "nome": "Zezinho",
   "email": "zezinho@fatec.com.br",
   "senha": "Aluno@1"
}

### 
// DELETE - Apaga um usuario através do id informado
DELETE {{baseURL}}/usuarios/{{id}}
Content-Type: application/json

###
// PUT - Altera um usuario pelo ID
PUT {{baseURL}}/usuarios/{{id}}
Content-Type: application/json

{
    "nome": "Carlos Miguel",
    "email": "cmiguel@uol.com",
    "senha": "carlos2@",
    "ativo": true,
    "tipo": "Profissional",
    "avatar": "https://ui-avatars.com/api/?background=3700B3&color=FFFFFF&name=Walter+Hugo+Cavana"
  }

###
// POST - Efetuar o Login
POST {{baseURL}}/usuarios/login
Content-Type: application/json

{
   "email": "zezinho@fatec.com.br",
   "senha": "Aluno@1"

}

###
// GET - Validar o token
GET {{baseURL}}/usuarios/token
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjE4YWZhNDU0YjE4YmFkYTY2NmE4NDE0In0sImlhdCI6MTYzNzY5MTk5OCwiZXhwIjoxNjM3NzI3OTk4fQ.mw-plPkz8fagYGn6mXZBthp4bstdPPTnGYHPCnkQrxo


