//Teste de Requisições REST - Usuários
@baseURL = http://localhost:4000/api
@id = 618ac4956ae534cb83972b23
###
// GET - Lista todos os usuários
GET {{baseURL}}/usuarios
Content-Type: application/json

###
// GET - Lista apenas um usuário pelo id
GET {{baseURL}}/usuarios/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo usuário
POST {{baseURL}}/usuarios
Content-Type: application/json

{
   "nome": "Walter Hugo Cavana",
   "email": "walteracavanahugo2@uol.com",
   "senha": "Walter2@",
   "ativo": true,
   "tipo": "Profissional",
   "avatar": "https://ui-avatars.com/api/?background=5B1333&color=fff&name=Walter+Cavana"
}

### 
// DELETE - Apaga um estudante através do id informado
DELETE {{baseURL}}/usuarios/{{id}}
Content-Type: application/json

###
// PUT - Altera um estudante pelo ID
PUT {{baseURL}}/usuarios/{{id}}
Content-Type: application/json

{
    "nome": "Walter Hugo Cavana Jr alves de Braga Neto oi",
    "email": "hugolima@uol.com",
    "senha": "Walter2@",
    "ativo": true,
    "tipo": "Profissional",
    "avatar": "https://ui-avatars.com/api/?background=3700B3&color=FFFFFF&name=Walter+Hugo+Cavana"
  }

###
// POST - Efetuar o Login
POST {{baseURL}}/usuarios/login
Content-Type: application/json

{
   "email": "walteracavanahugo2@uol.com",
   "senha": "Walter2@"

}

###
// POST - Validar o token
POST {{baseURL}}/usuarios/token
Content-Type: application/json
{
"access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjE4YWZhNDU0YjE4YmFkYTY2NmE4NDE0Iiwibm9tZSI6IldhbHRlciBIdWdvIENhdmFuYSIsInRpcG8iOiJQcm9maXNzaW9uYWwifSwiaWF0IjoxNjM2NTA0NzExLCJleHAiOjE2MzY1NDA3MTF9.DsjFCdhOLxE3J5fhVkg4DCE3vKdeBu65KMfr4IVqAxI"					
}

